### ISSUE TITLE
Broken on latest Chrome 96.0 on macOS

### ISSUE THREAD

**Issue by derwaldgeist** [markusenglund/react-switch#101]
I'm unsure if this is the same problem as #75, so I am reporting this separately.

With the recent Chrome version 96.0 on macOS, the switch functionality is more or less broken. I can enable a switch, and sometimes, I can also disable it again. But at least after a couple of user interactions (clicks), the switch starts to follow the mouse cursor instead of reacting on clicks. And even worse: if you have multiple switches on a page and click on another one, this starts following the mouse as well. So basically, you can make all switches move with the mouse pointer, which is a pretty strange UX.

It does not happen on iOS or Firefox. On Android, it kinda works, but sometimes the animations are missing.

(I did not change my code for quite some time, and also did upgrade to a newer React version. So I guess it's an incompatibility introduced by Chrome.)

My environment: Chrome 96.0 under macOS Monterey. Using `react-switch@^6.0.0`

**Comment by derwaldgeist** [comment]
I created a quick [YouTube video](https://youtu.be/hMNJ_f0ydjg) video to illustrate the problem.

In this video, each switch is clicked once. Afterwards, it follows the mouse pointer.

**Comment by markusenglund** [comment]
Hi, thanks for the report. Do you get the same problem on the [demo page](https://react-switch.netlify.app/)? If not, could you please fork this [sandbox](https://codesandbox.io/s/fervent-glade-0bqk8?file=/src/index.js)?

Unfortunately I don't have easy access to a MacOS device. I briefly tested the demo page on chrome 96 on macos via browserstack and couldn't reproduce.

**Comment by derwaldgeist** [comment]
Closing this. It seems to have been a temporary hick-up of Chrome which vanished after restarting my Mac.
