### ISSUE TITLE
Disabled - not changing the style.

### ISSUE THREAD

**Issue by juanpmarengo** [markusenglund/react-switch#12]
Expected behaviour: disabling the action without changing it's color to grey. 
Is there a way to achieve this?
Thanks in advance.

**Comment by markusenglund** [comment]
It's a bit of a hack, but you could do this:

Give the switch a className
```jsx
<Switch
  className="react-switch"
  // Other props
/>
```
Then override the opacity-styling in css
```css
.react-switch {
  opacity: 1 !important;
}
```

Hope that helps!

**Comment by juanpmarengo** [comment]
It works! Thanks!
