### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by chrismeyers** [markusenglund/react-switch#130]
Please add support for React 19.  The peer dependencies may just need to be updated, but I don't know if there are any breaking changes that need to be addressed.

Upgrade guide: https://react.dev/blog/2024/04/25/react-19-upgrade-guide

**Comment by markusenglund** [comment]
Hi Chris. I updated the peerDependency in 7.1.0. No other changes were required to remain compatible as far as I can tell. Thanks for reporting!

**Comment by chrismeyers** [comment]
Works great on React 19, thanks!
