### ISSUE TITLE
Label Issues

### ISSUE THREAD

**Issue by kinoli** [markusenglund/react-switch#14]
Usually, when a label is attached to a checkbox/radio and the user clicks on the label, it toggles the button. That functionality doesn't seem to work with this switch. It might be nice to add that in.

**Comment by markusenglund** [comment]
Yeah, I remember thinking the same thing when I first created this package. The `react-toggle` library achieves this by having an [invisible checkbox input](https://github.com/aaronshaf/react-toggle/blob/master/src/component/index.js#L149) hidden inside the component. That would be possible to implement in this package as well, although some other tweaks would be necessary for it to work.

I'm not sure if it's something we would want to do though. Clickable labels is more standards compliant, but it's not something that everyone wants. If someone really desires it, they can always add a separate click handler to their label text. I am undecided.

**Comment by markusenglund** [comment]
This was fixed in #17 and just released in v4.0.0! The label is now clickable.
