### ISSUE TITLE
some kind of Focus border

### ISSUE THREAD

**Issue by assafb81** [markusenglund/react-switch#16]
Hi,
I encounter this extra border:
![image](https://user-images.githubusercontent.com/28925534/46653254-317fb080-cbae-11e8-81fc-abe0b464e36f.png)

How Can I remove it?

Thanks

**Comment by markusenglund** [comment]
Which OS, device and browser are you using?

**Comment by assafb81** [comment]
I am saw it on chrome emulator and on iPad pro.

**Comment by assafb81** [comment]
with the demo I can't reproduce it
