### ISSUE TITLE
Value doesn't change if clicked on handle if Chrome not in focus

### ISSUE THREAD

**Issue by saitonakamura** [markusenglund/react-switch#21]
Repro:

1. Open [official demo](https://markusenglund.github.io/react-switch/) in a Chrome (I have version 70, but i think i've seen this on previous versions)
2. Open another application (i have Windows 10 though) and focus it
3. Click on handle -> doesn't trigger the change, just the focus

If you click not on the handle itself, it's working fine

#8 Can be related

Last Edge and Firefox also working fine

**Comment by markusenglund** [comment]
Now it's released in 4.0.0!

**Comment by saitonakamura** [comment]
That's really cool, thank you, I'll give it a try!
