### ISSUE TITLE
When clicking on handler, click event propagates.

### ISSUE THREAD

**Issue by yzaroui** [markusenglund/react-switch#29]
Hello,
I am using the switch inside a user component in a list.
Clicking on the user component displays the user details.

<img width="869" alt="switch in user component" src="https://user-images.githubusercontent.com/3058420/51599383-b5f90380-1eff-11e9-83f2-dc8f7eba5105.png">

**What should happen:**
Clicking on the switch (handle included) should toggle an attribute on the user without showing the user details.

**What happens instead:**
Clicking on the switch handle triggers displaying the user details (a callback on the user component).

Even when I add e.stopPropagation in the onChange callback, it still propagates.

This maybe related to [issue 21](https://github.com/markusenglund/react-switch/issues/21) but the solution provided there did not fix this propagation issue.

**Comment by Shravan89131** [comment]
Hello,
I am also facing the same issue. Does any have has a solution for this?

**Comment by drownbes** [comment]
@Shravan89131 Just wrap it with div and stop propagation on it.

```
<div onClick={e => e.stopPropagation()}>
<Switch>
</div>
```
