### ISSUE TITLE
Not disabled completely when disabling

### ISSUE THREAD

**Issue by jimitpatel** [markusenglund/react-switch#5]
```
import SwitchButton from 'react-switch'
<SwitchButton disabled=false height={20} width={48} className='react-switch' id='material-switch' />
```

Even though it is disabled, when I am dragging it, it is still working, but when I am clicking it, it is not working.

**Comment by markusenglund** [comment]
I see two issues with the code sample that you've provided:
1. You're not giving the switch a `checked` and `onChange` prop. Both of these are required for it to work properly.
2. You've set disabled to ´false´. That means the switch is *not* disabled. You should set disabled to ´true´ to disable the switch.

If you fix these things, I'm sure the package will work as advertised.

**Comment by jimitpatel** [comment]
Cool. Understood my problem. Although, above code was just a part of it. I messed with flag values for `disabled` and was changing it to `check` or `uncheck` on clicking it. Thanks a lot
