### ISSUE TITLE
Rewrite for Hooks / React 16.8?

### ISSUE THREAD

**Issue by djD-REK** [markusenglund/react-switch#51]
Hi,  Your component has the best functionality I've found in react switches or toggles.  Is it possible to use it as-is using hooks?  Is there a plan to include hooks support in the future?  Thanks!!!

**Comment by markusenglund** [comment]
Yeah, it's definitely possible. I'll make sure to add an example using hooks in the demo for the next release.

**Comment by usamamashkoor** [comment]
@markusenglund can we use it for React Hooks now?
