### ISSUE TITLE
Addition of an extra state so that it behaves as a tri state switch

### ISSUE THREAD

**Issue by vjr12** [markusenglund/react-switch#52]
Want to implement something like a switch that has three states, "ENABLED,PENDING,DISABLED" . Is it possible that something like this can be implemented

Something like this?
![Screenshot from 2019-08-13 17-14-01](https://user-images.githubusercontent.com/42905121/62939069-037e8480-bdee-11e9-8ca4-28d3df4ec6d7.png)

![Screenshot from 2019-08-13 17-16-48](https://user-images.githubusercontent.com/42905121/62939143-332d8c80-bdee-11e9-84a7-ea3594eb23e5.png)

![Screenshot from 2019-08-13 17-16-35](https://user-images.githubusercontent.com/42905121/62939174-404a7b80-bdee-11e9-8cbf-a724020b4571.png)

**Comment by djD-REK** [comment]
Yes, that type of Switch is super possible, though please tell me if you
figure out how to do it in react-switch!

I created a 3-way drag-and-drop switch here that starts in the middle
position but can be swiped left or right for my language learning game I'm
developing:

https://codesandbox.io/s/learn-penguin-app-prototype-github-master-qqtem

Best regards,
Derek

Derek R. Austin, PT, DPT, MS, BCTMB, CSCS

Join me on LinkedIn: https://www.linkedin.com/in/Derek-Austin

**Comment by velsonjr** [comment]
@djD-REK  Waiitng for the creator's comments. It would be great if you could find one:). Have searched a lot, but could not find one that actually matches the requirements:(

**Comment by markusenglund** [comment]
It's not supported to do currently.
I'm open to the idea but it seems like a big headache to implement and support since react-switch wasn't built with this use case in mind. It would probably have to involve adding a lot of new props that would only be used for this.

**Comment by duhaime** [comment]
@vjr12 could this be reopened? This would be a great addition to the library. At the very least the feature request should stay open so other developers could contribute this generalization of the ui...
