### ISSUE TITLE
height not working

### ISSUE THREAD

**Issue by Ahmed-Elswerky** [markusenglund/react-switch#53]
<Switch
                            defaultValue={false}
                            offColor="success"
                            offText="OFF"
                            onColor="success"
                            onText="ON"
                            height={10}
                          />

the default width and height are !important so those don't work

**Comment by CatalinaCampos** [comment]
I'm working with this and height is working! 

<Switch 
onChange={this.handleChange} 
checked={checked} 
height={10} />

**Comment by Ahmed-Elswerky** [comment]
ok thanks
