### ISSUE TITLE
Can we somehow add image to the round toggle switch?

### ISSUE THREAD

**Issue by alishajain7** [markusenglund/react-switch#57]
As per my UI design, I want to customise the toggle switch. Is there a way to do that?
Any help will be appreciated. Thanks

![toggle](https://user-images.githubusercontent.com/33221676/69343033-cd755a00-0c92-11ea-8085-1e922f7ec38c.JPG)

**Comment by saysmaster** [comment]
Any help on that. Our design needs that too.

![toggle-with-icon](https://user-images.githubusercontent.com/3409322/71564122-3b881a80-2aa4-11ea-9b85-58311c9089f9.jpg)

Thanks.

**Comment by sjarva** [comment]
It is fairly simple to add an icon to the handle is stead of the background area.
But, from a possible contributor's point of view, having answers to these questions would be helpful:

1. Would your design hope for two different icons (based on the state of the switch, one icon for checked, another for unchecked state) or would just the one icon be enough? (If there are two different icons, the transition from state to another will need more fine-tuning, it's a lot easier to have just one icon.)
2. Would the color of the icon change based on the switch state or stay the same?

**Comment by markusenglund** [comment]
Sorry for not responding earlier.

#73 has been merged and will be included in version 6.0.0. Closing the issue.
