### ISSUE TITLE
a11y: aria-checked

### ISSUE THREAD

**Issue by Stenbaek** [markusenglund/react-switch#58]
The input has role="switch", but has no corresponding aria-checked.

This is flagged for a site doing a Lighthouse accessibility audit.

<img width="587" alt="Screenshot 2019-12-16 at 14 50 17" src="https://user-images.githubusercontent.com/624812/70912134-9a18b780-2013-11ea-852c-c7276f2f651e.png">

**Comment by Stenbaek** [comment]
I just realized that {...rest} is being passed on to the input. I know that you can add it yourself then, but imo it should be handled out of the box.

**Comment by monicahung** [comment]
The ARIA specification states that the aria-checked attribute needs to be specified if using the switch role. 

https://www.w3.org/TR/wai-aria-1.2/#switch

**Comment by gh640** [comment]
@markusenglund It looks like you stopped maintaining this package... 😢  Do you have any plan to commit these pull requests?

**Comment by markusenglund** [comment]
I'm sorry for responding to this very late.

I've merged monicahung's PR. It will be deployed in a new release soon.

**Comment by bjackson** [comment]
I believe `aria-checked` should not be present on `input`s where `type="checkbox"` according to [ARIA guidelines](https://www.w3.org/TR/html-aria/#el-input-checkbox).
