### ISSUE TITLE
Time to update dependencies, maybe?

### ISSUE THREAD

**Issue by dreamyguy** [markusenglund/react-switch#66]
Since `package.json` lists **react** as `react: ^16.7.0` (released on 2018.12.20), I guessed my way to the closest **node** LTS at the time: `8.14.1` (released on 2018.12.18).

Based on that, I installed the dependencies locally and got the following result:

<img width="918" alt="Screenshot 2020-02-16 at 23 16 35" src="https://user-images.githubusercontent.com/1021849/74613852-b966ba80-5112-11ea-9671-c0d802387242.png">

That's a lot of time since then so this update might not be the most trivial, but maybe it's worth a try?

I usually hesitate to open PRs with so obtrusive changes, since they tend to not get merged...

**Comment by markusenglund** [comment]
Hi,

Yes, it's high time for an update. I've already done so myself and will be merged to master when I cut the release later this month.
