### ISSUE TITLE
Getting ESLintError for LABEL must have nesting, id and label-has-for types

### ISSUE THREAD

**Issue by gxwheel152** [markusenglund/react-switch#76]
I am getting ESLintError for LABEL must have nesting, id and label-has-for types. 

> esLint: warning  Form label must have ALL of the following types of associated control: nesting, id  jsx-a11y/label-has-for

I believe I've added in both the htmlFor & the aria-labeledby (after getting the error). My Switch Component was already nested within the label (per my understanding), but am still getting the error. 

Anything I'm missing. This is a newer error. 

`                <label htmlFor="viewSwitcher" id="view-switcher">
                  <h5 className={layoutStyles.heading}>
                    <Switch
                      id="viewSwitcher"
                      aria-labelledby="view-switcher"
                      tabindex="0"
                      onChange={toggleTeamView}
                      checked={state.isTeamViewOn}
                      className="react-switch"
                    />{" "}
                    {"   "} TEAM STATS
                  </h5>
                </label>
`

**Comment by markusenglund** [comment]
I don't know, I couldn't reproduce the problem
