### ISSUE TITLE
Rewrite or at least add Usage section for functional component with useStateHook()

### ISSUE THREAD

**Issue by kalmanh** [markusenglund/react-switch#86]
to bring this into 21 Century (React time :))

If interested - I can work on a PR?

**Comment by markusenglund** [comment]
Hi, I will not rewrite the component itself as a functional component with hooks, but adding an example in the demo that uses a functional component is a good idea. I would accept a PR if you did one.

PS. I'll make sure to respond in a more timely manner.

**Comment by markusenglund** [comment]
I ended up adding it myself.

**Comment by kalmanh** [comment]
Still not seeing it. Did you not push it out to the repo yet?

**Comment by VladimirTambovtsev** [comment]
Can anyone update the docs, please?
